<?php

namespace IK\Bundle\ParserBundle\Repository;

use Doctrine\ORM\EntityManager;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
    public function findByOldId(Array $ids) {
//        /** @var EntityManager $em */
//        $em = $this->getEntityManager();
//        $em->createQueryBuilder()
//            ->where('category.old_id in (:ids)')
//            ->setParameter('ids', $ids)
//            ->getQuery()->getResult();

        return $this->createQueryBuilder('category')
            ->where('category.old_id in (:ids)')
            ->setParameter('ids', $ids)
            ->getQuery()->getResult();
    }
}
