<?php

namespace IK\Bundle\ParserBundle\Repository;

/**
 * ColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorRepository extends \Doctrine\ORM\EntityRepository
{
}
